backend:
  name: git-gateway
  branch: master
media_folder: static/img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Carousel Images', name: 'image', widget: 'image'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Carousel'
            name: "carousel"
            widget: list
            fields:
              - { label: "Image", name: "image", widget: "image"}
      - label: 'About'
        name: 'about'
        file: 'content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }